[package]
name = "lazydb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.16.0"
termion = "1.5"
rand = "0.8.4"
redis = "0.21.1"
clap = "3.0.0-beta.4"